import type { Metadata } from "next";
import Header from "@/components/layouts/Header";
import localFont from "next/font/local";
import "./globals.css";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import Footer from "@/components/layouts/Footer";

const geistSans = localFont({
  src: "../assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const baseOpenGraph = {
  locale: 'en_US',
  type: 'website',
  siteName: 'Productic Company'
}

export const metadata: Metadata = {
  title: "StaticHub",
  description: "Generated by create next app",
  openGraph: baseOpenGraph
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
